export const mockOffers = [
  {
    id: "1",
    departure: "Casablanca",
    arrival: "Marrakech",
    date: "25/04/2025",
    productType: "Fruits et légumes",
    availableKg: 180,
    pricePerKg: 2.0,
    temperature: "8°C à 12°C",
    driverName: "Youssef El Mansouri",
    driverAvatar: "/placeholder.svg",
  },
  {
    id: "2",
    departure: "Agadir",
    arrival: "Rabat",
    date: "26/04/2025",
    productType: "Poissons et fruits de mer",
    availableKg: 100,
    pricePerKg: 3.5,
    temperature: "0°C à 2°C",
    driverName: "Fatima Zahra Bennani",
    driverAvatar: "/placeholder.svg",
  },
  {
    id: "3",
    departure: "Tanger",
    arrival: "Fès",
    date: "27/04/2025",
    productType: "Produits laitiers",
    availableKg: 140,
    pricePerKg: 1.9,
    temperature: "2°C à 4°C",
    driverName: "Omar El Idrissi",
    driverAvatar: "/placeholder.svg",
  },
  {
    id: "4",
    departure: "Oujda",
    arrival: "Casablanca",
    date: "28/04/2025",
    productType: "Viandes",
    availableKg: 90,
    pricePerKg: 4.2,
    temperature: "0°C à 2°C",
    driverName: "Imane Bakkali",
    driverAvatar: "/placeholder.svg",
  },
  {
    id: "5",
    departure: "Essaouira",
    arrival: "Meknès",
    date: "29/04/2025",
    productType: "Fruits et légumes",
    availableKg: 160,
    pricePerKg: 1.7,
    temperature: "8°C à 12°C",
    driverName: "Rachid Amrani",
    driverAvatar: "/placeholder.svg",
  },
  {
    id: "6",
    departure: "Fès",
    arrival: "Chefchaouen",
    date: "30/04/2025",
    productType: "Fromages artisanaux",
    availableKg: 60,
    pricePerKg: 3.0,
    temperature: "4°C à 6°C",
    driverName: "Nadia Chafiq",
    driverAvatar: "/placeholder.svg",
  },
  {
    id: "7",
    departure: "Tétouan",
    arrival: "Tanger",
    date: "01/05/2025",
    productType: "Herbes fraîches",
    availableKg: 70,
    pricePerKg: 1.2,
    temperature: "10°C à 12°C",
    driverName: "Karim Boutayeb",
    driverAvatar: "/placeholder.svg",
  },
  {
    id: "8",
    departure: "Khouribga",
    arrival: "Rabat",
    date: "02/05/2025",
    productType: "Fruits secs",
    availableKg: 200,
    pricePerKg: 2.1,
    temperature: "Ambiante",
    driverName: "Lamiae Mernissi",
    driverAvatar: "/placeholder.svg",
  },
  {
    id: "9",
    departure: "Beni Mellal",
    arrival: "Casablanca",
    date: "03/05/2025",
    productType: "Légumes bio",
    availableKg: 180,
    pricePerKg: 2.3,
    temperature: "8°C à 10°C",
    driverName: "Hicham Ait Taleb",
    driverAvatar: "/placeholder.svg",
  },
  {
    id: "10",
    departure: "Rabat",
    arrival: "Kenitra",
    date: "04/05/2025",
    productType: "Produits laitiers",
    availableKg: 130,
    pricePerKg: 1.8,
    temperature: "4°C à 6°C",
    driverName: "Meryem El Fassi",
    driverAvatar: "/placeholder.svg",
  },
  {
    id: "11",
    departure: "Laâyoune",
    arrival: "Agadir",
    date: "05/05/2025",
    productType: "Poissons",
    availableKg: 90,
    pricePerKg: 3.9,
    temperature: "-1°C à 1°C",
    driverName: "Abdelhak Bennis",
    driverAvatar: "/placeholder.svg",
  },
  {
    id: "12",
    departure: "Tan-Tan",
    arrival: "Tiznit",
    date: "06/05/2025",
    productType: "Dattes",
    availableKg: 120,
    pricePerKg: 2.5,
    temperature: "Ambiante",
    driverName: "Soukaina Idrissi",
    driverAvatar: "/placeholder.svg",
  },
  {
    id: "13",
    departure: "Settat",
    arrival: "Marrakech",
    date: "07/05/2025",
    productType: "Miel pur",
    availableKg: 50,
    pricePerKg: 5.0,
    temperature: "Ambiante",
    driverName: "Anouar Essamadi",
    driverAvatar: "/placeholder.svg",
  },
  {
    id: "14",
    departure: "Al Hoceïma",
    arrival: "Taza",
    date: "08/05/2025",
    productType: "Poissons et fruits de mer",
    availableKg: 110,
    pricePerKg: 3.8,
    temperature: "0°C à 2°C",
    driverName: "Zineb Rami",
    driverAvatar: "/placeholder.svg",
  },
  {
    id: "15",
    departure: "Nador",
    arrival: "Fès",
    date: "09/05/2025",
    productType: "Fruits tropicaux",
    availableKg: 170,
    pricePerKg: 2.6,
    temperature: "6°C à 8°C",
    driverName: "Samir Mouline",
    driverAvatar: "/placeholder.svg",
  },
];
